export const GET_FILM_ORIGINALS = "GET_FILM_ORIGINALS";
export const GET_FILM_TRENDING = "GET_FILM_TRENDING";
export const GET_FILM_TOPRATE = "GET_FILM_TOPRATE";
export const GET_FILM_ACTION = "GET_FILM_ACTION";
export const GET_FILM_COMEDY = "GET_FILM_COMEDY";
export const GET_FILM_HORROR = "GET_FILM_HORROR";
export const GET_SEARCH_MOVIES = "GET_SEARCH_MOVIES";

export const SET_MOVIE_DETAIL = "SET_MOVIE_DETAIL";
